export interface ModuleTheory {
  n: number;
  titulo: string;
  objetivo: string;
  teoria: string[];
  exemplosSimples: string[];
  exemplosCeramica: string[];
  passoAPasso: string[];
  errosComuns: string[];
  dicas: string[];
  resumo: string;
  checklist: string[];
}

export const THEORY: ModuleTheory[] = [
{ n:1, titulo:"Fundamentos da Proporção", objetivo:"Entender o que é razão e proporção antes de aprender a regra de três.",
teoria:["Razão é a comparação entre duas grandezas, escrita como A/B ou A:B. Por exemplo, se em uma caixa há 3 peças de piso azul para cada 5 peças de piso bege, a razão é 3:5.",
"Proporção é a igualdade entre duas razões: A/B = C/D. Ela diz que duas comparações mantêm a mesma relação, mesmo com números diferentes.",
"Toda a regra de três é construída em cima dessa ideia: encontrar um valor desconhecido que mantenha a mesma proporção de uma situação conhecida."],
exemplosSimples:["Se a razão entre maçãs e laranjas é 2:3, e há 4 maçãs, existem 6 laranjas (a razão foi multiplicada por 2)."],
exemplosCeramica:["Em um lote, a razão entre paletes de piso polido e piso fosco é 3:5. Se há 12 paletes de polido, há 20 de fosco, mantendo a proporção."],
passoAPasso:["Passo 1: identifique as duas grandezas comparadas.","Passo 2: escreva a razão conhecida (ex: 3:5).","Passo 3: descubra o fator multiplicador usando o valor conhecido.","Passo 4: aplique o mesmo fator ao outro lado da razão."],
errosComuns:["Inverter a ordem da razão (trocar A por B).","Somar em vez de multiplicar pelo fator correto.","Confundir razão com diferença entre os números."],
dicas:["Sempre escreva a razão na mesma ordem em que o problema descreve as grandezas.","Desenhe a razão como uma fração — isso ajuda a visualizar o fator multiplicador."],
resumo:"Razão compara duas grandezas; proporção iguala duas razões. Esse é o alicerce de toda regra de três.",
checklist:["Sei o que é uma razão","Sei o que é uma proporção","Consigo encontrar o fator multiplicador entre duas razões"]},

{ n:2, titulo:"Regra de Três do Zero", objetivo:"Aprender a montar corretamente a tabela de regra de três simples, identificando A, B, C e X.",
teoria:["A regra de três simples resolve problemas com duas grandezas proporcionais, onde conhecemos três valores e precisamos descobrir o quarto (X).",
"A tabela é montada em duas colunas: cada linha representa uma situação. A primeira linha tem os valores conhecidos (A e B); a segunda linha tem um valor conhecido (C) e o valor desconhecido (X).",
"O segredo está em colocar cada grandeza sempre na mesma coluna: por exemplo, sempre 'quantidade de máquinas' na coluna da esquerda e 'peças produzidas' na coluna da direita."],
exemplosSimples:["3 máquinas produzem 90 peças. Quantas peças 5 máquinas produzem? Tabela: 3→90 / 5→X."],
exemplosCeramica:["4 prensas produzem 800 peças por turno. Quantas peças 6 prensas produziriam, no mesmo ritmo? Monta-se: 4→800 / 6→X."],
passoAPasso:["Passo 1: identifique as duas grandezas do problema.","Passo 2: monte duas colunas, uma para cada grandeza.","Passo 3: preencha a primeira linha com os valores conhecidos (A e B).","Passo 4: preencha a segunda linha com o valor conhecido (C) e X no lugar do desconhecido.","Passo 5: multiplique cruzado (A×X = B×C) e isole X."],
errosComuns:["Trocar a grandeza de coluna no meio da tabela.","Multiplicar na mesma linha em vez de cruzado.","Esquecer de verificar se a relação é direta ou inversa antes de multiplicar."],
dicas:["Nomeie as colunas antes de preencher os números — isso evita trocar a grandeza de lugar.","Confira sempre: 'o que aumenta, o que diminui?' antes de multiplicar."],
resumo:"Montar a tabela corretamente, com cada grandeza na mesma coluna, é o passo mais importante da regra de três.",
checklist:["Sei identificar as duas grandezas de um problema","Sei montar a tabela com A, B, C e X","Sei aplicar a multiplicação cruzada"]},

{ n:3, titulo:"Grandezas Diretamente Proporcionais", objetivo:"Reconhecer e resolver problemas onde as duas grandezas aumentam ou diminuem juntas.",
teoria:["Duas grandezas são diretamente proporcionais quando, ao multiplicar uma delas por um número, a outra também é multiplicada pelo mesmo número.",
"Exemplo: mais horas de produção → mais peças produzidas (mantendo o ritmo). Se dobra o tempo, dobra a produção.",
"Na tabela de regra de três direta, a multiplicação cruzada é feita normalmente: A×X = B×C."],
exemplosSimples:["Se 2 horas produzem 100 peças, 4 horas produzem 200 peças (o dobro do tempo, o dobro da produção)."],
exemplosCeramica:["Uma esteira aplica esmalte em 300 peças em 3 horas. Em 6 horas, aplicará esmalte em 600 peças, mantido o ritmo."],
passoAPasso:["Passo 1: confirme que as grandezas crescem juntas.","Passo 2: monte a tabela normalmente.","Passo 3: multiplique cruzado sem inverter nenhuma coluna.","Passo 4: confira se a resposta faz sentido (maior tempo → maior produção)."],
errosComuns:["Aplicar a regra inversa por engano, invertendo uma das colunas.","Esquecer de manter a mesma unidade de tempo nos dois lados."],
dicas:["Pergunte sempre: 'se uma aumenta, a outra aumenta também?' Se sim, é direta."],
resumo:"Nas grandezas diretas, ambas crescem ou diminuem juntas — a multiplicação cruzada é direta, sem inversão.",
checklist:["Reconheço uma relação diretamente proporcional","Sei resolver regra de três direta","Sei conferir se o resultado faz sentido"]},

{ n:4, titulo:"Grandezas Inversamente Proporcionais", objetivo:"Reconhecer e resolver problemas onde uma grandeza aumenta enquanto a outra diminui.",
teoria:["Duas grandezas são inversamente proporcionais quando, ao multiplicar uma por um número, a outra é dividida pelo mesmo número.",
"Exemplo clássico: mais operadores trabalhando → menos dias para terminar a mesma ordem de produção.",
"Para resolver, multiplicamos os valores da MESMA linha (em vez de cruzar): A×B (situação 1) deve ser igual a C×X (situação 2)."],
exemplosSimples:["4 pessoas terminam um serviço em 8 dias. 8 pessoas terminariam em 4 dias (dobrou a equipe, caiu pela metade o tempo)."],
exemplosCeramica:["5 operadores concluem uma ordem em 10 dias. Com 10 operadores, a mesma ordem seria concluída em 5 dias."],
passoAPasso:["Passo 1: confirme que uma grandeza sobe enquanto a outra desce.","Passo 2: monte a tabela normalmente.","Passo 3: multiplique os valores da mesma linha (não cruze): A×B = C×X.","Passo 4: isole X dividindo pelo valor conhecido restante."],
errosComuns:["Aplicar multiplicação cruzada (regra direta) por engano em uma situação inversa.","Confundir qual grandeza aumenta e qual diminui."],
dicas:["Pergunte sempre: 'se uma aumenta, a outra diminui?' Se sim, é inversa — e a conta muda."],
resumo:"Nas grandezas inversas, uma sobe enquanto a outra desce — multiplicamos na mesma linha, não cruzado.",
checklist:["Reconheço uma relação inversamente proporcional","Sei resolver regra de três inversa","Sei diferenciar direta de inversa em um problema novo"]},

{ n:5, titulo:"Identificando o Tipo de Relação", objetivo:"Desenvolver a habilidade de reconhecer, diante de qualquer problema, se a relação é direta ou inversa.",
teoria:["Antes de montar qualquer regra de três, é essencial parar e perguntar: 'o que acontece com uma grandeza quando a outra aumenta?'",
"Se as duas aumentam juntas (ou diminuem juntas), a relação é direta.",
"Se uma aumenta enquanto a outra diminui, a relação é inversa.",
"Essa identificação evita o erro mais comum em regra de três: aplicar o procedimento errado (cruzado quando deveria ser direto na linha, ou vice-versa)."],
exemplosSimples:["Mais velocidade de uma esteira → menos tempo para percorrer a mesma distância: inversa."],
exemplosCeramica:["Mais horas de forno ligado → mais peças queimadas: direta. Mais velocidade da esteira do forno → menos tempo de queima: inversa."],
passoAPasso:["Passo 1: leia o problema com atenção, identificando as duas grandezas.","Passo 2: imagine o que aconteceria se uma delas dobrasse.","Passo 3: veja se a outra também dobraria (direta) ou cairia pela metade (inversa).","Passo 4: só então monte a tabela com o procedimento correto."],
errosComuns:["Assumir que toda regra de três é direta.","Não testar mentalmente o que aconteceria ao aumentar uma das grandezas."],
dicas:["Sempre que tiver dúvida, monte um exemplo mental simples com números pequenos antes de calcular com os números reais do problema."],
resumo:"Identificar corretamente se a relação é direta ou inversa é o passo que evita a maioria dos erros em regra de três.",
checklist:["Sei testar mentalmente se uma relação é direta ou inversa","Não confio apenas na 'aparência' do problema","Verifico antes de montar a tabela"]},

{ n:6, titulo:"Unidades de Medida", objetivo:"Dominar as conversões de unidades mais usadas no PCP de uma cerâmica antes de aplicá-las em regra de três.",
teoria:["Muitos erros em regra de três não são de proporção, mas de unidade: comparar kg com toneladas, ou minutos com horas, sem converter antes.",
"Principais conversões usadas no PCP: 1 tonelada = 1.000 kg; 1 kg = 1.000 g; 1 m² = 10.000 cm²; 1 hora = 60 minutos; 1 minuto = 60 segundos.",
"Antes de montar a regra de três, sempre deixe as duas grandezas na mesma unidade."],
exemplosSimples:["2.500 kg equivalem a 2,5 toneladas (dividir por 1.000)."],
exemplosCeramica:["Um pedido de matéria-prima de 4.800 kg deve ser comparado com a capacidade do silo, informada em toneladas: 4.800 kg = 4,8 t."],
passoAPasso:["Passo 1: identifique a unidade de cada valor do problema.","Passo 2: verifique se as unidades são compatíveis.","Passo 3: converta para a mesma unidade antes de montar a tabela.","Passo 4: resolva a regra de três normalmente."],
errosComuns:["Multiplicar ou dividir pelo fator de conversão errado (ex: multiplicar por 1.000 quando deveria dividir).","Misturar minutos e horas na mesma conta sem converter."],
dicas:["Escreva a unidade ao lado de cada número durante o cálculo — isso ajuda a perceber conversões esquecidas."],
resumo:"Antes de qualquer regra de três, confira e converta as unidades para evitar erros silenciosos no resultado.",
checklist:["Sei converter kg em toneladas e vice-versa","Sei converter minutos em horas e vice-versa","Sei converter m² em cm² quando necessário"]},

{ n:7, titulo:"Produção por Tempo", objetivo:"Aplicar regra de três direta para calcular produção esperada em diferentes intervalos de tempo.",
teoria:["Um dos usos mais comuns da regra de três no PCP é estimar quanto será produzido em um período diferente do informado, mantendo a mesma taxa de produção.",
"Essa é uma relação diretamente proporcional: mais tempo de operação, mais peças ou m² produzidos, desde que o ritmo se mantenha constante."],
exemplosSimples:["Se uma linha produz 50 peças por hora, em 8 horas produzirá 400 peças."],
exemplosCeramica:["Uma linha de prensagem produz 480 peças em 4 horas. Mantendo o ritmo, em 7 horas produzirá 840 peças."],
passoAPasso:["Passo 1: calcule (ou identifique) a taxa de produção por hora.","Passo 2: multiplique a taxa pelo novo tempo desejado.","Passo 3: confira se a unidade de tempo é a mesma nos dois lados."],
errosComuns:["Usar a produção total em vez da taxa por hora ao multiplicar.","Esquecer de manter a mesma unidade de tempo."],
dicas:["Sempre que possível, calcule primeiro 'quanto se produz por hora' — isso simplifica qualquer variação de tempo pedida depois."],
resumo:"Produção e tempo, no mesmo ritmo, formam uma relação direta: basta manter a taxa e multiplicar pelo novo tempo.",
checklist:["Sei calcular a taxa de produção por hora","Sei projetar produção para um tempo diferente","Sei verificar a coerência da unidade de tempo"]},

{ n:8, titulo:"Tempo Necessário para Produzir", objetivo:"Calcular quanto tempo é necessário para atingir uma meta de produção, dada a taxa de produção.",
teoria:["Esse módulo trabalha o caminho inverso do anterior: em vez de saber o tempo e calcular a produção, sabemos a meta de produção e precisamos calcular o tempo necessário.",
"A fórmula chave é: tempo = meta de produção ÷ taxa de produção por hora."],
exemplosSimples:["Se a taxa é de 40 m²/hora e a meta é 320 m², o tempo necessário é 320 ÷ 40 = 8 horas."],
exemplosCeramica:["Uma linha produz 60 m² por hora. Para atender um pedido de 480 m², são necessárias 480 ÷ 60 = 8 horas de produção."],
passoAPasso:["Passo 1: identifique a taxa de produção por hora.","Passo 2: identifique a meta total de produção.","Passo 3: divida a meta pela taxa para obter o tempo.","Passo 4: confira se o resultado está em horas (ou converta, se o problema pedir outra unidade)."],
errosComuns:["Multiplicar em vez de dividir a meta pela taxa.","Confundir taxa por hora com taxa por turno."],
dicas:["Sempre escreva a unidade do resultado esperado (horas, dias) antes de calcular — isso ajuda a escolher entre multiplicar e dividir."],
resumo:"Para descobrir o tempo necessário, divida a meta de produção pela taxa de produção.",
checklist:["Sei calcular o tempo necessário para uma meta de produção","Sei diferenciar quando dividir e quando multiplicar","Sei conferir a unidade do resultado"]},

{ n:9, titulo:"Massa e Quantidade", objetivo:"Relacionar o consumo de massa cerâmica por peça com a quantidade total produzida.",
teoria:["Cada peça de piso consome uma quantidade específica de massa cerâmica na prensagem. Multiplicando esse consumo pela quantidade de peças, obtemos o consumo total de massa necessário para a produção.",
"Essa é uma relação diretamente proporcional: mais peças, mais massa consumida, na mesma proporção."],
exemplosSimples:["Se cada peça consome 2,5 kg de massa, 100 peças consomem 250 kg."],
exemplosCeramica:["Cada peça de piso consome 3,2 kg de massa cerâmica. Para produzir 600 peças, são necessários 3,2 × 600 = 1.920 kg de massa."],
passoAPasso:["Passo 1: identifique o consumo de massa por peça.","Passo 2: identifique a quantidade de peças a produzir.","Passo 3: multiplique consumo por peça × quantidade de peças."],
errosComuns:["Dividir em vez de multiplicar o consumo por peça pela quantidade.","Confundir consumo por peça com consumo por lote."],
dicas:["Sempre confira: 'o consumo por peça está em kg? A quantidade está em peças?' antes de multiplicar."],
resumo:"O consumo total de massa é sempre o consumo por peça multiplicado pela quantidade de peças produzidas.",
checklist:["Sei calcular o consumo total de massa a partir do consumo por peça","Sei aplicar essa lógica a outros insumos (esmalte, embalagem)"]},

{ n:10, titulo:"Área e Produção de Pisos", objetivo:"Converter entre metros quadrados de piso e número de peças, considerando o formato utilizado.",
teoria:["Cada formato de piso cobre uma quantidade específica de peças por metro quadrado. Por exemplo, um piso de 30x30 cm cobre cerca de 11 peças por m² (aproximadamente, dependendo da junta).",
"Para simplificar os cálculos, o PCP costuma trabalhar com valores já calculados de 'peças por m²' de cada formato, usados diretamente na regra de três."],
exemplosSimples:["Se um formato equivale a 5 peças por m², para cobrir 200 m² são necessárias 1.000 peças."],
exemplosCeramica:["Um pedido de 350 m² de piso, em um formato de 6 peças por m², exige 350 × 6 = 2.100 peças."],
passoAPasso:["Passo 1: identifique quantas peças equivalem a 1 m² no formato utilizado.","Passo 2: identifique a área total desejada.","Passo 3: multiplique peças por m² × área total."],
errosComuns:["Trocar 'peças por m²' pela área de uma peça individual.","Esquecer de considerar perdas de corte ou assentamento (tratadas em outro módulo)."],
dicas:["Sempre confirme o valor de 'peças por m²' do formato específico antes de calcular — ele muda conforme o tamanho da peça."],
resumo:"Peças totais = peças por m² do formato × área total desejada.",
checklist:["Sei converter área em número de peças","Sei que o fator 'peças por m²' depende do formato utilizado"]},

{ n:11, titulo:"Rendimento", objetivo:"Calcular quanto de material de entrada realmente se transforma em produto final aproveitável.",
teoria:["Nem toda a massa ou matéria-prima que entra no processo se transforma em produto final: parte é perdida em etapas como secagem, queima e classificação.",
"Rendimento é o percentual da entrada que realmente vira produto aproveitável. Produto final = entrada × rendimento (em decimal)."],
exemplosSimples:["Se o rendimento é 90% e entram 1.000 kg, o produto final aproveitável é 900 kg."],
exemplosCeramica:["Um lote de 2.400 kg de massa passa por prensagem e secagem com rendimento de 88%. O produto aproveitável é 2.400 × 0,88 = 2.112 kg."],
passoAPasso:["Passo 1: identifique a quantidade de entrada no processo.","Passo 2: identifique o percentual de rendimento.","Passo 3: multiplique entrada × rendimento (em decimal, ex: 88% = 0,88)."],
errosComuns:["Confundir rendimento com perda (usar o percentual errado).","Multiplicar pela perda em vez de pelo rendimento."],
dicas:["Lembre-se: rendimento + perda = 100%. Se você tem a perda, calcule o rendimento antes de multiplicar."],
resumo:"Produto final aproveitável = quantidade de entrada × percentual de rendimento do processo.",
checklist:["Sei calcular o produto final a partir do rendimento do processo","Sei diferenciar rendimento de perda"]},

{ n:12, titulo:"Perdas e Refugos", objetivo:"Calcular quanto é preciso produzir a mais para compensar perdas e refugos, garantindo a entrega da quantidade desejada.",
teoria:["Enquanto o módulo de rendimento calcula 'quanto sobra' a partir da entrada, este módulo resolve o caminho inverso: 'quanto preciso produzir' para garantir uma entrega, já considerando que parte será perdida.",
"Fórmula: produção necessária = quantidade desejada ÷ (1 − percentual de perda em decimal)."],
exemplosSimples:["Se preciso entregar 900 peças boas e a perda é 10%, preciso produzir 900 ÷ 0,90 = 1.000 peças."],
exemplosCeramica:["A fábrica precisa entregar 5.000 peças boas de piso, com 8% de perda histórica na classificação. A produção necessária é 5.000 ÷ 0,92 ≈ 5.435 peças."],
passoAPasso:["Passo 1: identifique a quantidade final desejada (peças boas).","Passo 2: identifique o percentual de perda.","Passo 3: calcule 1 menos a perda (percentual que sobra bom).","Passo 4: divida a quantidade desejada pelo percentual que sobra bom."],
errosComuns:["Multiplicar pela perda em vez de dividir pelo percentual que sobra.","Somar a perda diretamente à quantidade desejada (isso subestima o necessário)."],
dicas:["Cuidado: somar simplesmente a % de perda à meta não é o cálculo correto, pois a perda incide sobre o total produzido, não sobre a meta."],
resumo:"Para compensar perdas, divida a quantidade desejada pelo percentual que efetivamente sobra boa (100% − perda).",
checklist:["Sei calcular quanto produzir para compensar uma perda esperada","Sei por que dividir, e não somar, o percentual de perda"]},

{ n:13, titulo:"Consumo de Matéria-Prima", objetivo:"Calcular o total de matéria-prima necessário para atingir uma meta de produção.",
teoria:["Cada tonelada de piso produzida consome uma quantidade específica de matéria-prima (argila, feldspato, aditivos), já considerando perdas normais do processo.",
"Esse consumo por tonelada é usado para planejar compras e estoques: consumo total = consumo por tonelada × toneladas a produzir."],
exemplosSimples:["Se o consumo é 1.020 kg por tonelada de produto, para produzir 10 toneladas são necessários 10.200 kg."],
exemplosCeramica:["A produção de 1 tonelada de piso consome 1.030 kg de matéria-prima. Para uma meta de 25 toneladas, o consumo total é 1.030 × 25 = 25.750 kg."],
passoAPasso:["Passo 1: identifique o consumo de matéria-prima por tonelada.","Passo 2: identifique a meta de produção em toneladas.","Passo 3: multiplique consumo por tonelada × toneladas planejadas."],
errosComuns:["Usar o consumo por peça em vez de por tonelada, misturando unidades.","Esquecer que o consumo por tonelada já inclui perdas — não aplicar perda duas vezes."],
dicas:["Sempre confirme em qual unidade de produção (tonelada, m², peça) o índice de consumo foi definido."],
resumo:"O consumo total de matéria-prima é o índice de consumo por unidade de produção multiplicado pela meta de produção.",
checklist:["Sei calcular o consumo total de matéria-prima para uma meta de produção","Sei evitar aplicar a perda duas vezes"]},

{ n:14, titulo:"Capacidade Produtiva", objetivo:"Diferenciar capacidade nominal de produção real, aplicando o percentual de eficiência da linha.",
teoria:["Capacidade nominal é o que uma linha produziria em condições ideais, sem paradas. Na prática, paradas, ajustes e pequenas perdas reduzem esse número — o que chamamos de eficiência (ou OEE simplificado).",
"Produção real esperada = capacidade nominal × percentual de eficiência."],
exemplosSimples:["Se a capacidade nominal é 1.000 unidades/dia e a eficiência é 80%, a produção real esperada é 800 unidades/dia."],
exemplosCeramica:["Uma linha tem capacidade nominal de 6.000 m²/dia, mas opera com eficiência real de 85% devido a paradas de manutenção. A produção real esperada é 6.000 × 0,85 = 5.100 m²/dia."],
passoAPasso:["Passo 1: identifique a capacidade nominal.","Passo 2: identifique o percentual de eficiência real.","Passo 3: multiplique capacidade nominal × eficiência (em decimal)."],
errosComuns:["Usar a capacidade nominal diretamente no planejamento, ignorando a eficiência real.","Confundir eficiência com percentual de perda de produto."],
dicas:["Ao planejar entregas, sempre use a produção real esperada — nunca a capacidade nominal — para evitar atrasos."],
resumo:"Produção real esperada = capacidade nominal × eficiência real da linha.",
checklist:["Sei diferenciar capacidade nominal de produção real","Sei calcular a produção real a partir da eficiência"]},

{ n:15, titulo:"Turnos e Programação", objetivo:"Calcular a produção total considerando múltiplos turnos e dias de operação.",
teoria:["Quando a fábrica opera em mais de um turno por dia, a produção total é a soma da produção de cada turno — e, se for programada para vários dias, multiplicamos também pelos dias.",
"Produção total = produção por turno × número de turnos × número de dias (quando aplicável)."],
exemplosSimples:["Se cada turno produz 500 peças e há 2 turnos por dia, a produção diária é 1.000 peças."],
exemplosCeramica:["Cada turno da linha de esmaltação produz 1.200 peças. Operando 3 turnos por dia durante 5 dias, a produção total é 1.200 × 3 × 5 = 18.000 peças."],
passoAPasso:["Passo 1: identifique a produção por turno.","Passo 2: identifique o número de turnos por dia.","Passo 3: identifique o número de dias, se o problema pedir um período.","Passo 4: multiplique todos os valores."],
errosComuns:["Esquecer de multiplicar pelo número de dias quando o problema pede um período maior que um dia.","Confundir produção por turno com produção por hora."],
dicas:["Ao ler o problema, sublinhe mentalmente: por turno, por dia, por período — isso evita esquecer um dos fatores da multiplicação."],
resumo:"A produção total em um período é o produto entre produção por turno, número de turnos e número de dias.",
checklist:["Sei calcular a produção diária considerando múltiplos turnos","Sei estender o cálculo para vários dias de programação"]},

{ n:16, titulo:"Estoque e Cobertura", objetivo:"Calcular quantos dias de produção um estoque de insumo é capaz de sustentar.",
teoria:["Cobertura de estoque é uma medida essencial de PCP: indica por quantos dias a fábrica pode operar com o estoque atual, sem nova reposição.",
"Fórmula: dias de cobertura = estoque disponível ÷ consumo médio diário."],
exemplosSimples:["Se há 3.000 kg em estoque e o consumo diário é de 500 kg, a cobertura é de 6 dias."],
exemplosCeramica:["O estoque de esmalte é de 4.800 kg, com consumo médio diário de 600 kg. A cobertura do estoque é 4.800 ÷ 600 = 8 dias de produção."],
passoAPasso:["Passo 1: identifique o estoque disponível.","Passo 2: identifique o consumo médio diário.","Passo 3: divida o estoque pelo consumo diário."],
errosComuns:["Inverter a divisão (consumo ÷ estoque em vez de estoque ÷ consumo).","Usar consumo semanal ou mensal sem converter para consumo diário."],
dicas:["Sempre confirme se o consumo informado já está na base 'por dia' antes de aplicar a fórmula diretamente."],
resumo:"Dias de cobertura = estoque disponível dividido pelo consumo médio diário do insumo.",
checklist:["Sei calcular quantos dias um estoque cobre","Sei identificar quando é necessário converter o consumo para base diária"]},

{ n:17, titulo:"PCP Aplicado à Cerâmica", objetivo:"Comparar produção planejada com produção realizada, usando percentuais de atingimento.",
teoria:["No dia a dia do PCP, comparamos frequentemente o que foi planejado em uma ordem de produção com o que efetivamente foi realizado, expresso como um percentual de atingimento da meta.",
"Produção realizada = produção planejada × percentual atingido (em decimal)."],
exemplosSimples:["Se o planejado era 1.000 unidades e foram atingidos 90%, a produção realizada foi 900 unidades."],
exemplosCeramica:["Uma ordem de produção planejava 8.000 m² de piso. A linha atingiu 93% do planejado devido a uma parada de manutenção. A produção realizada foi 8.000 × 0,93 = 7.440 m²."],
passoAPasso:["Passo 1: identifique a produção planejada.","Passo 2: identifique o percentual de atingimento informado.","Passo 3: multiplique planejado × percentual (em decimal)."],
errosComuns:["Confundir percentual de atingimento com percentual de perda.","Aplicar o percentual sobre a produção realizada anterior, em vez de sobre o planejado."],
dicas:["Sempre releia o problema para confirmar sobre qual valor (planejado ou realizado) o percentual está sendo aplicado."],
resumo:"A produção realizada é sempre a produção planejada multiplicada pelo percentual de atingimento da meta.",
checklist:["Sei calcular a produção realizada a partir do percentual de atingimento","Sei identificar sobre qual valor o percentual incide"]},

{ n:18, titulo:"Problemas Intermediários de PCP", objetivo:"Resolver problemas com duas etapas de cálculo, combinando produção e perdas.",
teoria:["A partir deste módulo, os problemas combinam mais de um conceito já estudado — por exemplo, calcular a produção bruta por tempo e, em seguida, aplicar uma perda sobre esse resultado.",
"A habilidade central aqui é organizar o raciocínio em passos claros, resolvendo uma etapa de cada vez, sem tentar calcular tudo de uma vez só."],
exemplosSimples:["Uma linha produz 100 peças/hora por 5 horas (500 peças brutas). Com 10% de refugo, restam 450 peças boas."],
exemplosCeramica:["Uma linha produz 250 peças/hora, operando 6 horas (1.500 peças brutas). Com 8% de refugo na classificação, restam 1.500 × 0,92 = 1.380 peças boas."],
passoAPasso:["Passo 1: resolva a primeira etapa (geralmente produção bruta por tempo).","Passo 2: use o resultado da primeira etapa como entrada da segunda etapa (geralmente uma perda ou rendimento).","Passo 3: confira se cada etapa faz sentido isoladamente antes de prosseguir."],
errosComuns:["Aplicar a perda sobre o valor errado (por hora, em vez de sobre o total produzido).","Tentar resolver as duas etapas em uma única conta, gerando confusão."],
dicas:["Escreva o resultado de cada etapa separadamente, com sua unidade, antes de seguir para a próxima."],
resumo:"Problemas com duas etapas exigem organização: resolva uma etapa por vez e use o resultado de uma como entrada da próxima.",
checklist:["Sei separar um problema em etapas menores","Sei usar o resultado de uma etapa como entrada da próxima"]},

{ n:19, titulo:"Problemas Avançados", objetivo:"Resolver problemas com três ou mais etapas, combinando conversão de unidades, produção e perdas.",
teoria:["Os problemas avançados de PCP raramente vêm prontos: exigem converter unidades, calcular produção e aplicar perdas, tudo na mesma questão.",
"A estratégia continua sendo a mesma dos módulos anteriores: dividir o problema em etapas pequenas e resolver uma de cada vez, na ordem em que os dados aparecem no raciocínio (não necessariamente na ordem em que aparecem no texto)."],
exemplosSimples:["Uma linha produz 20 m²/hora por 5 horas (100 m²). Cada m² tem 6 peças (600 peças brutas). Com 10% de perda, restam 540 peças boas."],
exemplosCeramica:["Uma linha produz 30 m²/hora, opera 6 horas (180 m²). Cada m² equivale a 8 peças (1.440 peças brutas). Com 9% de perda na classificação, restam 1.440 × 0,91 ≈ 1.310 peças boas."],
passoAPasso:["Passo 1: identifique todas as etapas necessárias antes de calcular qualquer coisa.","Passo 2: resolva a etapa de produção por tempo primeiro.","Passo 3: converta o resultado para a unidade necessária (ex: m² para peças).","Passo 4: aplique a perda ou o rendimento por último."],
errosComuns:["Aplicar a perda antes da conversão de unidade, na ordem errada.","Perder-se na quantidade de dados e esquecer uma das etapas."],
dicas:["Antes de calcular, liste em uma linha o caminho que você vai seguir: 'produção → conversão → perda'. Isso organiza o raciocínio."],
resumo:"Problemas avançados combinam várias etapas — planeje o caminho de cálculo antes de começar a resolver.",
checklist:["Sei planejar a sequência de cálculo antes de resolver","Sei combinar conversão de unidade com produção e perdas em um mesmo problema"]},

{ n:20, titulo:"Desafio Final de PCP", objetivo:"Integrar todos os conceitos estudados para resolver cenários realistas e completos de PCP.",
teoria:["Este módulo final apresenta cenários com múltiplas informações — algumas necessárias para o cálculo, outras apenas contextuais. Parte da habilidade profissional em PCP é identificar quais dados realmente importam para a pergunta feita.",
"Isso reflete a realidade da fábrica: relatórios de produção, capacidade e estoque trazem muito mais informação do que é preciso para responder uma pergunta específica."],
exemplosSimples:["Um relatório traz capacidade, eficiência, turnos e consumo de matéria-prima, mas a pergunta é apenas sobre cobertura de estoque: só o estoque e o consumo diário importam."],
exemplosCeramica:["A fábrica informa capacidade nominal, eficiência, número de turnos, consumo diário de matéria-prima e estoque atual — mas a pergunta pede apenas quantos dias o estoque cobre. A resposta usa somente estoque ÷ consumo diário."],
passoAPasso:["Passo 1: leia a pergunta final antes de tentar entender todos os dados.","Passo 2: identifique exatamente quais grandezas a pergunta relaciona.","Passo 3: separe, entre todos os dados apresentados, apenas os que são realmente necessários.","Passo 4: resolva com o método adequado (direta, inversa, ou combinação de etapas)."],
errosComuns:["Tentar usar todos os dados do enunciado, mesmo os que não se relacionam com a pergunta.","Não reler a pergunta final antes de finalizar o cálculo."],
dicas:["Releia a pergunta uma segunda vez depois de calcular, para confirmar que respondeu exatamente o que foi pedido."],
resumo:"No PCP profissional, saber filtrar quais dados são relevantes para cada pergunta é tão importante quanto saber calcular.",
checklist:["Sei identificar quais dados de um cenário são realmente necessários","Sei aplicar, de forma integrada, tudo o que aprendi nos módulos anteriores"]},
];
